VERSION = "0.1.0"
TITLE = "The Art of Order - v{} (preview build)".format(VERSION)
FPS = 120
RESOLUTION_X = 1024
RESOLUTION_Y = 768
TILESIZE = 32
GRIDWIDTH = RESOLUTION_X / TILESIZE
GRIDHEIGHT = RESOLUTION_Y / TILESIZE
