VERSION = "0.2.0"
TITLE = "The Art of Order - v{} (preview build)".format(VERSION)
FPS = 120
RESOLUTION_X = 1600
RESOLUTION_Y = 900
TILESIZE = 32
GRIDWIDTH = RESOLUTION_X / TILESIZE
GRIDHEIGHT = RESOLUTION_Y / TILESIZE
